### PR TITLE
Updates for NewsML-G2 2.29 to be voted at Spring Meeting 2020.

### PR DESCRIPTION
**Pull request by bquinn**

### CODE REVIEW

**Review by davecompton — CHANGES_REQUESTED** [review]
In FlexOrganisationPropType:
flexAttributes should be replaced by qualifyingAttributes, but I see:
      
      <xs:attributeGroup ref="flexAttributes"/>
This is for the 4x cases marked as 'X' below:
1 examples/NewsML-G2_2.29-spec-All-Power.xsd X
2 specification/NewsML-G2_2.29-spec-All-Power.xsd X
3 specification/*_1/NewsML-G2_2.29-spec-Framework-Power_1.xsd X
4 specification/*_1/NewsML-G2_2.29-spec-KnowledgeItem-Power_1.xsd
5 specification/individual/NewsML-G2_2.29-spec-Framework-Power.xsd X
6 specification/individual/NewsML-G2_2.29-spec-KnowledgeItem-Power.xsd

Also ... should there be a change for NewsML-G2_2.29-spec-All-Power**_1**.xsd ?

**Comment by bquinn** [comment]
Thanks for spotting it - I made that change.

I'm not sure what you're asking re the reference to NewsML-G2_2.29-spec-All-Power**_1**.xsd? It's the same file as specification/NewsML-G2_2.29-spec-All-Power.xsd, I checked in 2.28 and it's the same there.

**Comment by davecompton** [comment]
> I'm not sure what you're asking re the reference to NewsML-G2_2.29-spec-All-Power**_1**.xsd?
I didn't see NewsML-G2_2.29-spec-All-Power_1.xsd in the changed file list, but I did see other _1 files changed. Does NewsML-G2_2.29-spec-All-Power.xsd simply get copied to NewsML-G2_2.29-spec-All-Power_1.xsd at some stage?

**Comment by bquinn** [comment]
It is there: https://github.com/iptc/newsml-g2/blob/newsml2.29/specification/XML-Schema_FileVersion_1/NewsML-G2_2.29-spec-All-Power_1.xsd 

It's created in _1 by `release-tools/create-power-xsd-from-framework-xsd.sh` and then copied into the parent dir.

I guess it just gets lost in the huge list of changed files.

Maybe in the future we can change the process again so we don't use version numbers in our working versions of the schema files, so we can actually see what has changed from one version to another using git diffs much more easily.

**Comment by davecompton** [comment]
> It is there: https://github.com/iptc/newsml-g2/blob/newsml2.29/specification/XML-Schema_FileVersion_1/NewsML-G2_2.29-spec-All-Power_1.xsd

Ok I see it now - must have been too energetic scrolling down yesterday :) Will take a further look asap later today after some calls.

**Review by davecompton — APPROVED** [review]
FlexOrganisationPropType still has 'oraganisation', but the rest looks correct.

Also extracted specification/NewsML-G2_2.29-spec-All-Power.xsd: My 2.29 tests validate against this.

**Comment by bquinn** [comment]
Thanks! And I've fixed the "oraganisation" typo. I'll send out this version.

**Pull request merged**
